import os
from pptx import Presentation
from pptx.util import Inches, Pt

def create_ppt(content_text, output_ppt_path, title="Course Presentation"):
    """Converts structured text into a PowerPoint presentation."""
    try:
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        title_shape.text = title
        subtitle_shape.text = "Generated by EduDigest AI"

        # Content Slides
        # Simple heuristic: Split content by double newlines or lines starting with '#'
        sections = content_text.split('\n\n')
        
        for section in sections:
            if not section.strip():
                continue
                
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            lines = section.strip().split('\n')
            title_text = lines[0].replace('#', '').strip()
            body_text = "\n".join(lines[1:])
            
            title_shape.text = title_text[:100] # Cap title length
            tf = body_shape.text_frame
            tf.text = body_text
            
        prs.save(output_ppt_path)
        print(f"PPT created successfully: {output_ppt_path}")
        return True
    except Exception as e:
        print(f"Error during PPT creation: {e}")
        return False

if __name__ == "__main__":
    pass
